---
knit: "bookdown::preview_chapter"
---

# Events

The format for listing an R event is

  * Date: [event name & link](http://www.example.com). Town, Country. [Recordings here & link](http://www.example.com) [Slides here & link](http://www.example.com)

## 2019 {-}

### January

  * January 15-18: [rstudio::conf](https://www.rstudio.com/conference/). Austin, USA.

### July

  * July (probably): useR! 2019. Toulouse, France.

## 2018 {-}

### June

 *  June 1-2: [R/Finance 2018](http://www.rinfinance.com). Chicago, USA.
 *  June 2: [CascadiaRConf](https://www.cascadiarconf.com). Portland, USA.

### July

 * July 2-5: [WhyR? 2018](http://whyr2018.pl/). Wroclaw, Poland.
 * July 4-6: [7eme rencontres R](https://r2018-rennes.sciencesconf.org). Rennes, France.
 * July 9-13: [R Software Fundamentals with Applications to Statistical Analyses and Modelling](http://www.sastat.org.za/sites/default/files/inline-files/2018-04-08_ShortCourse-RSoftwareFundamentals_Version-Noticeboards%28WithURL%29.pdf). Johannesburg, South Africa
 * July 10-13: [useR! 2018](https://user2018.r-project.org/). Brisbane, Australia.
 * July: [Noreast'R Conference](http://noreastrconf.com/). Providence, USA.

### September

 * September 4-5: [LatinR 2018](http://latin-r.com/). Buenos Aires, Argentina.
 * September 11-13: [EARL London 2018](https://earlconf.com/london/). London, United Kingdom.
 * September 12-14: [The Use of R in Official Statistics](https://www.aanmelder.nl/uros2018). Hague, Netherlands.
 
### November

 * November 7: [EARL Seattle](https://earlconf.com/boston). Seattle, USA.
 * November 9: [EARL Houston](https://earlconf.com/boston). Houston, USA.
 * November 13: [EARL Boston](https://earlconf.com/boston). Boston, USA.

## Archive - 2018 {-}

  * January 31, Feb 1-3: [rstudio::conf](https://www.rstudio.com/conference/). San Diego, USA. ([Recordings here](https://www.rstudio.com/resources/webinars/#cd2efd7cff89930bc))
  * March 17th: [SatRday](http://capetown2018.satrdays.org/). Cape Town, South Africa. ([Recordings here](https://www.youtube.com/watch?v=bVweO74kvtc&list=PLQPtslMzGu4oDr6hjKm1aQ2XN7P35vCbk))
  * April 3-6: [Workshop: Chain event graphs in modelling complex health and medical data](http://www.stats.uct.ac.za/stats/study/postgrad/shortcourses/chaineventgraphs). Cape Town, South Africa
  * April 16-26: [Short Course: Mathematical Modelling for Infectious Diseases](http://www.stats.uct.ac.za/stats/study/postgrad/shortcourses/MMID). Cape Town, South Africa
  * April 20-21: [New York R Conference](http://rstats.nyc/). New York, USA.
  * May: [The European #rstats Users Meeting](http://2018.erum.io/). Budapest, Hungary.  ([Recordings here](https://www.youtube.com/watch?list=PLUBl0DoLa5SAo_XRnkQA5GtEORg9K7kMh&v=4XxOUPgs9tc))
  * May 22: [R Day](http://rday.leg.ufpr.br/). Curitiba, Brazil.

## Archive - 2017 {-}

 * January 11-14: [rstudio::conf](https://www.rstudio.com/conference/). Kissmmee, USA. ([Recordings here](https://www.rstudio.com/resources/webinars/#ed21d83e49156bae4))
  * February 16-18: [satRday](http://satrdays.org/capetown2017/). Cape Town, South Africa. ([Recordings here]())
  * March 4: [#ODDZurich Hackathon](http://zurich-r-user-group.github.io/hackathon.html). Zurich, Switzerland.
  * March 24-25: [Women in Machine Learning & Data Science](http://www.wimldsdatadive.com/hackathons/2). New York, USA.
  * April 21-22: [New York R Conference 2017](http://www.rstats.nyc). New York, USA. ([Recordings here](https://www.rstats.nyc/2017/))
  * May 19-20: [R/Finance 2017](http://www.rinfinance.com). Chicago, USA. ([Recordings here](https://channel9.msdn.com/Events/RFinance/RFinance-2017))
  * May 25-26: [R à Québec 2017](http://raquebec.ulaval.ca/2017/). Québec, Canada.
  * May 25-26: [ROpenSci Unconference](https://ropensci.org/community/events.html). Los Angeles, USA.
  * May 28-Jun 2: [WOMBAT MeDaScIn 2017](http://www.datasciencemelbourne.com/medascin2017/). Melbourne, Australia.
  * June 3: [CascadiaRconf](https://cascadiarconf.com/2017). Portland, USA.
  * June 5-7: [EARL](http://www.mango-solutions.com/wp/2017/01/earl-2017-abstract-submissions-open-for-san-francisco-and-london-san-francisco-dates-and-venue-announced/). San Francisco, USA.
   * June 8: [R in Insurance](https://rininsurance17.sciencesconf.org/). Paris, France. 
  * July 4-7: [UseR! 2017](http://www.user2017.brussels/). Brussels, Belgium. [Recordings](https://channel9.msdn.com/events/useR-international-R-User-conferences/)
  * July 5: [Riot](http://riotworkshop.github.io/). Co-located with useR! 2017.
  * July 27-28: [BioC 2017](https://www.bioconductor.org/help/course-materials/2017/BioC2017/). Boston, USA.
  * September 13-15: [EARL London 2017](https://earlconf.com/london/). London, UK.
  * November 1-3: [EARL Boston 2017](https://earlconf.com/boston/). Boston, USA.
  * November 6-7: [New Challenges for Statistical Software - The Use of R in Official Statistics](http://www.r-project.ro/conference2017/). Bucharest, Romania.
  * November 8-9: [R Kenntnis-Tage 2017](http://www.eoda.de/de/R-Kenntnis-Tage.html). Kassel, Germany.
  * November 16-17: [Bioconductor Asia](https://www.abacbs.org/conference-workshops#bioc2017-link). Adelaide, Australia.
  * December 5-6: [Bioconductor European Conference](https://bioconductor.org/help/course-materials/2017/BioCEurope/). Cambridge, UK.

## Archive - 2016 {-}

  * April: [New York R Conference 2016](http://www.rstats.nyc). New York, USA. ([Recordings here](https://www.rstats.nyc/2017/))
  * May: [R/Finance 2016](http://www.rinfinance.com). Chicago, USA.
  * July: [UseR! 2016](http://user2016.org/). Stanford, USA. ([Recordings here](https://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016))
  * September: [EARL London 2016](https://earlconf.com/london/). London, UK.
  * September: [The first satRday conference](http://budapest.satrdays.org). Budapest, Hungary.
  * October: [European R users meeting](http://erum.ue.poznan.pl/). Poznan, Poland.
  * November: [EARL Boston 2016](https://earlconf.com/boston/). Boston, USA.
  * December: [European Bioconductor Developers' Meeting](http://scicore.ch/events/eurobioc2016/). Basel, Switzerland.
